---
title: "AI Superpowers by Kai-Fu Lee"
author: "Nils Gandlau"
date: "10 11 2020"
output: 
  tufte::tufte_html: default
---

## AI Superpowers by Kai-Fu Lee

Es gibt viele Bücher über AI. Aber es gibt wenige, die von sehr glaubwürdigen Autoren geschrieben werden. Kai-Fu Lee ist einer von diesen. Er war *der* weltweit führende Forscher in Speech Recognition und belegte später Führungspositionen bei Apple, Microsoft und Google. Kurz gesagt: Der Typ hat's drauf.

Hier ein paar meiner Take-Aways:

* Das Kopieren von amerikanischen Techunternehmen wie Google, Amazon, Facebook, Twitter, Uber wird oft als etwas Verwerfliches abgestempelt. Das Gegenteil ist aber der Fall. Die Chinesen kopieren zwar die Kernideen (Suchmaschine, Soziales Netzwerk, Kurznachrichtendienst), optimieren diese aber für den chinesischen Markt. Das funktioniert, denn westliche Unternehmen sind so arrogant sind zu glauben, dass das selbe Produkt (z.B. Google) in allen Ländern der Welt gleichermaßen genutzt wird. Es ist aber tatsächlich so, dass z.B. Chinesen anders "Googlen" wie Amerikaner. Und genau diese regionalen Unterschieden machen sich die vermeintlichen Kopien zu nutze.

* Für eine Wirtschaft sind viele gute AI Engineers wertvoller als wenige geniale AI Scientists. Denn es ist die Mischung aus Gründern und soliden AI Engineers, die die theoretische Forschung nehmen und in real-world economic value übersetzen.

* China hat eine größere Menge an Daten. In China wird *alles* über das Smartphone gesteuert. Noch viel mehr als dies bei uns der Fall ist. Beispielsweise wurde im Finanzwesen der Zwischenschritt über Kreditkarten übersprungen, und man ist stattdessen direkt von Cash zu Mobile Payments übergegangen. Selbst der kleinste Kiosk bietet die Option an, mit dem Smartphone zu bezahlen. Dadurch fällt eine riesige Menge an Daten *aus der phyischen Welt* an: was, wann, wie oft und wo kaufe ich. Zu dem gibt es viel mehr Online-To-Offline Businesses. Das sind Geschäftsmodelle bei denen online bestellt und  offline geliefert wird (z.B. Ride Hailing, Massagen, Essenslieferdienste).
```{marginfigure}
Ja, anscheinend kann man sich in China Massagen bestellen.
```
Insgesamt ist in China also sowohl die Menge als auch die Art von Daten anders im Vergleich zu solchen, die die amerikanischen Tech-Unternehmen sammeln. Amerikanische Tech-Unternehmen sammeln überwiegend Daten aus dem eigenen Ecosystem: die Anzahl der Likes auf Facebook, die Kategorie von YouTube-Videos. 

* Kai-Fu Lee hält Universal Basic Income (UBI) für suboptimal. Er sieht es u.a. als eine Schnelllösung, die auch deswegen gerade in Silcon Valley so beliebt ist, da sie eine einfache Lösung darstellt, um die gesellschaftliche Misgunst, welche durch die monetäre Umverteilung zugunsten der AI-Giganten entsteht, reduziert. Stattdessen schlägt er vor, dass Menschen monetär belohnt werden sollen, wenn sie Gutes für die Community tun. Beispielsweise wenn Sie in einer Schule eine Kunst-AG führen. Oder einen lokalen Flohmarkt organisieren. Oder sich als Jugend-Trainer engagieren. Die Anreize sollen so gesetzt werden, dass ein gemeinschaftlicheres Leben gefördert wird.

* Kai-Fu Lee hat sein Leben sehr rational und optimiert geführt. Er sagt von sich selbst, dass er rund um die Uhr gearbeitet hat. Er hat seine Zeit immer so eingeteilt, um Einfluss und Erfolg zu maximieren. Er hat dabei automatisch menschliche Beziehungen, darunter die zu seiner Frau und Kind, vernachlässigt. Erst durch eine krebsbedingte Nahtoderfahrung hat er realisiert, dass das die falsche Strategie ist. Stattdessen plädiert er jetzt für mehr Liebe. Er sagt, es entspräche *nicht* dem Sinn des Lebens, jede Situation einer Kosten-Nutzen-Analyse zu unterziehen. Wenn man dies tut, versteht man den Kern des Menschseins nicht, und steuert langfristig auf ein unerfülltes, unglückliches Leben zu.
